### ISSUE TITLE
Color attribute

### ISSUE THREAD

**Issue by Batwho** [TombstoneTumbleweedArt/import-ply-as-verts#10]
Hi Tombstone,

Thank you very much for sharing this script. It's really helpful along with your youtube video there for a blender newbie.

I'm just wondering could this show the point color correctly with just points coordinates and their color given as input? For my file it couldn't show the color correctly as it shown in open3d. 

Blender gives me this:
![image](https://user-images.githubusercontent.com/56781672/214229067-0fad05ca-9120-4ce3-a49b-8f4399f4ccd3.png)
With open3d's image as:
![image](https://user-images.githubusercontent.com/56781672/214229201-08b14ee0-8be2-40d9-9aa4-6dc28bc47b8e.png)

My nodes connection is here and I would really appreciate if you could take a look at this specific case!
![image](https://user-images.githubusercontent.com/56781672/214228860-191907ea-8a0c-4c85-9883-892477d5e77f.png)
![image](https://user-images.githubusercontent.com/56781672/214228923-31345f18-ff58-47fe-b3ea-fd6a7277f83e.png)
(The ply file is here
[table.zip](https://github.com/TombstoneTumbleweedArt/import-ply-as-verts/files/10487004/table.zip)
 )

Best regards,
Batwho

**Comment by TombstoneTumbleweedArt** [comment]
Hello! Glad you find the thing useful 😀  I'm not sure why your data is displaying the way it is, I'll load it up and see what happens.

~Michael P.
________________________________
From: Tony Qian ***@***.***>
Sent: Monday, January 23, 2023 11:52:14 PM
To: TombstoneTumbleweedArt/import-ply-as-verts ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TombstoneTumbleweedArt/import-ply-as-verts] Color attribute (Issue #10)


Hi Tombstone,

Thank you very much for sharing this script. It's really helpful along with your youtube video there for a blender newbie.

I'm just wondering could this show the point color correctly with just points coordinates and their color given as input? For my file it couldn't show the color correctly as it shown in open3d.

Blender gives me this:
[image]<https://user-images.githubusercontent.com/56781672/214229067-0fad05ca-9120-4ce3-a49b-8f4399f4ccd3.png>
With open3d's image as:
[image]<https://user-images.githubusercontent.com/56781672/214229201-08b14ee0-8be2-40d9-9aa4-6dc28bc47b8e.png>

My nodes connection is here and I would really appreciate if you could take a look at this specific case!
[image]<https://user-images.githubusercontent.com/56781672/214228860-191907ea-8a0c-4c85-9883-892477d5e77f.png>
[image]<https://user-images.githubusercontent.com/56781672/214228923-31345f18-ff58-47fe-b3ea-fd6a7277f83e.png>
(The ply file is here
table.zip<https://github.com/TombstoneTumbleweedArt/import-ply-as-verts/files/10487004/table.zip>
)

Best regards,
Batwho

**Comment by farukahmet** [comment]
Hello, sorry for butting in a month later, but I came across this page while trying out the add-on (thank you, btw!) so I thought I'd point out the problem just in case: 

You (@Batwho) are trying to read the color attribute from "Geometry", which means vertices and edges and faces... while you only have _instances_ coming from **Instances on Points**. Either switching the **Attribute** node to "Instancer" mode, or using a **Realize Instances** to turn them into meshes would show the colors (first method is faster though of course):

![image](https://user-images.githubusercontent.com/20796719/221540178-36de7833-26d6-4ffd-b5f0-afabed43e037.png)

**Comment by Batwho** [comment]
Thank you @farukahmet  very much! It works now.
