### ISSUE TITLE
how can I install this on Mint ?

### ISSUE THREAD

**Issue by gordielachance** [TombstoneTumbleweedArt/import-ply-as-verts#14]
Hello, on Mint, the original plugin is located at something like

`snap/blender/3915/3.6/scripts/addons/io_mesh_ply/import_ply.py`

snaps are not editable.  Even when running `sudo nemo`, I can't edit those files.

How could I use your plugin ?

**Comment by TombstoneTumbleweedArt** [comment]
Hi! Thank you for writing.  In the several years of this project you're the first Linux user to contact us, and I had no idea the usual install-hack was blocked by sudo.

Not to worry! The 3.0 version of the addon is now a proper Addon that just installs like normal, along with a number of improvements.  We're a couple days from public release but I'll send you the new version ahead of that, likely today as there's just a bit of documentation to wrap up.


~Michael P.
________________________________
From: gordielachance ***@***.***>
Sent: Tuesday, September 19, 2023 11:13:55 AM
To: TombstoneTumbleweedArt/import-ply-as-verts ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TombstoneTumbleweedArt/import-ply-as-verts] how can I install this on Mint ? (Issue #14)


Hello, on Mint, the original plugin is located at something like

snap/blender/3915/3.6/scripts/addons/io_mesh_ply/import_ply.py

snaps are not editable. Even when running sudo nemo, I can't edit those files.

How could I use your plugin ?

**Comment by TombstoneTumbleweedArt** [comment]
The manual isn't quite done but here's the very latest build 🙂
Just unzip the IPAV-3 file, not the .zip inside, that's the Addon.
________________________________
From: gordielachance ***@***.***>
Sent: Tuesday, September 19, 2023 11:13 AM
To: TombstoneTumbleweedArt/import-ply-as-verts ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TombstoneTumbleweedArt/import-ply-as-verts] how can I install this on Mint ? (Issue #14)


Hello, on Mint, the original plugin is located at something like

snap/blender/3915/3.6/scripts/addons/io_mesh_ply/import_ply.py

snaps are not editable. Even when running sudo nemo, I can't edit those files.

How could I use your plugin ?

**Comment by gordielachance** [comment]
Thanks!  + I finally found out, by installing Blender without using snap and it worked.
Still surprised to be the first linux user :).

**Comment by TombstoneTumbleweedArt** [comment]
I had wondered if the snap might be the thing, good to know! Yeah, the mailing list is up to 3 now 😁

~Michael P.
________________________________
