### ISSUE TITLE
Color Attribute Issue

### ISSUE THREAD

**Issue by fredfred888** [TombstoneTumbleweedArt/import-ply-as-verts#19]
Hello,

first of all thanks a lot for the add-on and manual ! It's super useful.

I am an absolute noob on blender so probably my question will be stupid (and I hope there is an easy mistake I made that explains it all)

I followed all the steps listed in the Manual and everything worked perfectly until the color part. I imported a PLY from Polycam, checked ignore faces, the Col attribute do appear in the Data infos and yet in the material when I connect the attribute node with name set on "Col" to the Principled BSDF no colors appears on the point cloud. The render is set to Cycles. I also tryed to create a new node like in the manual (Add-Input-Attributes-Col) but the "Attributes" option doesn't even appear as you can see on the caps

![homme dans rue_1 1 1](https://github.com/TombstoneTumbleweedArt/import-ply-as-verts/assets/166435635/e089c855-9c0b-40d0-96ff-b113376a4479)

![homme dans rue_2](https://github.com/TombstoneTumbleweedArt/import-ply-as-verts/assets/166435635/07684763-572c-4799-a369-18c44885562c)
 below.

![homme dans rue_3](https://github.com/TombstoneTumbleweedArt/import-ply-as-verts/assets/166435635/c6ab2e82-8b49-452e-8f1b-be093429f4e6)

Maybe it comes from the PLY itself ? Or it is a render issue ? 

Thanks a lot for your time,

Fred

**Comment by TombstoneTumbleweedArt** [comment]
Hello Fred! Sorry the thing is giving you issues.  From the screenshots it looks like you've done everything correctly and thus I suspect the PLY.  If possible, send the model (or a link) directly to me at mprost17@hotmail.com and I'll be able to diagnose it.  There are a _LOT_ of variations of PLY out in the wild and sometimes it's necessary to tweak the importer to allow for new warts :)

**Comment by fredfred888** [comment]
Thanks a lot for the reply !
Okay I send you the PLY, I scanned it and downloaded it from Polycam so maybe it comes from the app ?

**Comment by vivi-gomez** [comment]
I guest I have the same problem. Any information about it?
I am importing a gaussian splatting ply from spotshot

**Comment by TombstoneTumbleweedArt** [comment]
Although my addon will (usually) load a Gaussian PLY, it's not equipped to translate the data into something Blender can use.  [This Addon](https://github.com/ReshotAI/gaussian-splatting-blender-addon) looks like it should do the trick.
