### ISSUE TITLE
Colors problem

### ISSUE THREAD

**Issue by Tonysa87** [TombstoneTumbleweedArt/import-ply-as-verts#6]
Hi!
I've tryed writing on the youtube video but seems the commet are disappeared.

The problem I was asking is that i can't get the color attribute to the points, I've defined the shader with the "attribute" "Col" as base color, and then the geometry node both with instance or mesh to points, but the points still has no colors

May I ask for help?
Thanks :)
![Cattura](https://user-images.githubusercontent.com/101409643/159244589-0f30fa4c-3689-4d2e-bb35-e2b8db5677b5.JPG)

**Comment by TombstoneTumbleweedArt** [comment]
You can _always_ ask for help :)
Try downloading and reinstalling the two script files from the repo and restart Blender.   If that doesn't do it, post a screenshot of your Geometry Nodes Panel (particularly the Spreadsheet from the upper left) and I'll be able to diagnose it.

**Comment by Tonysa87** [comment]
![image](https://user-images.githubusercontent.com/101409643/159326317-7901b84c-7d4b-4717-9268-4cb839215a1c.png)
It worked! 21milion points with now issue at all! very fluid indeed! 

The problem was originated in the ply vertex mesh generated in metashape with the flag on "convert color to 8bit rgb", with that enabled the colors was buggish.

**Comment by TombstoneTumbleweedArt** [comment]
Superb! That's a beautiful cloud 😀
