### ISSUE TITLE
does it change coordinates?

### ISSUE THREAD

**Issue by bgpantojar** [TombstoneTumbleweedArt/import-ply-as-verts#8]
Hello,

Thanks for such nice tool.

I have some problem when import the pointcloud as it seems it modifies the coordinates while importing. In the image, you can see that in blender (left) the two models do not overlap as they should. When open the models on meshlab it does work (right image). Is this a problem that can be solved?

![Screenshot from 2022-07-21 10-28-11](https://user-images.githubusercontent.com/35929939/180168184-c8631636-44af-4ae2-b3e6-2346bff176e2.png)

Best,
Bryan

**Comment by TombstoneTumbleweedArt** [comment]
Thank you for the email!

I've had the same issue on occasion, not really sure why that happens as it's sporadic.

Try snapping the 3d cursor to world origin, then snap each model to the cursor. Hopefully that will line them up correctly.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Bryan German Pantoja Rosero ***@***.***>
Sent: Thursday, July 21, 2022 1:30:46 AM
To: TombstoneTumbleweedArt/import-ply-as-verts ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TombstoneTumbleweedArt/import-ply-as-verts] does it change coordinates? (Issue #8)


Hello,

Thanks for such nice tool.

I have some problem when import the pointcloud as it seems it modifies the coordinates while importing. In the image, you can see that in blender (left) the two models do not overlap as they should. When open the models on meshlab it does work (right image). Is this a problem that can be solved?

[Screenshot from 2022-07-21 10-28-11]<https://user-images.githubusercontent.com/35929939/180168184-c8631636-44af-4ae2-b3e6-2346bff176e2.png>

Best,
Bryan

**Comment by bgpantojar** [comment]
Thanks for your reply.

That's a pity. Unfortunately, the snap solution does not work for me as also the point cloud coordinates are rotated. 

Best,
Bryan

**Comment by TombstoneTumbleweedArt** [comment]
If you are comfortable sharing your ply file with me (or another exhibiting the same behavior) I will pull it through the debugger and see if we can't get this working definitively.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bgpantojar** [comment]
Sure thing.. in this link you can find one of the examples that have this problem

https://u.pcloud.link/publink/show?code=kZDaYQVZrgaEQJI4yqpaE1NyDVRek86LIim7

Thanks a lot!

**Comment by TombstoneTumbleweedArt** [comment]
Thank you! I had meant to circle back to this issue eventually but I'm pretty sure I had completely forgotten 🤣.  Fewer bugs are always better!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bgpantojar** [comment]
Cool... so no modification to your .ply files was necessary?

I think you are trying to show me some screenshots, but I cannot see them. A see the next.

![Screenshot from 2022-08-02 10-02-29](https://user-images.githubusercontent.com/35929939/182324242-b3e67477-4f37-4fa1-9fb6-e9afa0a12b41.png)

**Comment by bgpantojar** [comment]
Now I got it.. thanks a lot.. works for me as well but just with the newimporter... the former one still had some issues.. THanks a lot!
