### ISSUE TITLE
Emission column after colors? (or just extra column in general)

### ISSUE THREAD

**Issue by beanachew** [TombstoneTumbleweedArt/import-ply-as-verts#9]
I've been working on a ply writer for some particle simulation data which can map one attribute to RGB, another to alpha, and a third to emission. With very little coding experience myself, I've been working on a personal set of edits to this reader for an additional column but I figure this may be something useful to others as well, hence why I bring it as a suggestion here.

**Comment by tibicen** [comment]
I had the same need on my projects. Especially with lidar data and point classification. Would be perfect to import additional rows of data into blender. Would be perfect to import it as for instance Float or Vector. I'd be happy to help with this if @TombstoneTumbleweedArt will agree.
![obraz](https://user-images.githubusercontent.com/5797670/211300459-4eedf2c3-64b8-4350-9e33-70dd9ae489ab.png)

**Comment by TombstoneTumbleweedArt** [comment]
Sorry this has been so long in the reply, finally getting things organized on this end.  Ms. Jarvis has very neatly programmed this capability and it is currently being merged. 🥇

**Comment by TombstoneTumbleweedArt** [comment]
The new release does this very nicely :)
